language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6

    packages:
      - g++-4.8
      - gcc-4.8
      - clang-3.6
      - clang-format-3.6
      - libboost-system1.54-dev
      - libboost-date-time1.54-dev
      - libboost-random1.54-dev

before_install:
  # install cpplint
  - curl https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py > /tmp/cpplint.py
  - sudo mv /tmp/cpplint.py /usr/local/bin/
  - sudo chmod 755 /usr/local/bin/cpplint.py
  # download file
  - mkdir -p tmp
  - curl https://cmake.org/files/v3.5/cmake-3.5.0.tar.gz > tmp/cmake-3.5.0.tar.gz
  # finish before
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR

install:
  - sudo script/build.sh
  
script:
  - make cpplint
  - ls -l bin
  - bin/processwarp --help
