language: cpp

compiler:
  - clang

before_install:
  - sudo apt-get install -y clang git doxygen libssl-dev
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -yqq
  - sudo apt-get install cmake g++-4.8
  # install socket.io
  - sudo apt-get install -y libboost1.55-dev libboost-system1.55-dev libboost-date-time1.55-dev libboost-random1.55-dev
  - git clone --recurse-submodules https://github.com/socketio/socket.io-client-cpp.git
  - cd socket.io-client-cpp
  - sed -i -e 's/cmake_minimum_required(VERSION 3.1.0/cmake_minimum_required(VERSION 2.8.12/' ./CMakeLists.txt
  - cmake -D CMAKE_CXX_FLAGS=-std=c++11 .
  - make
  - make install
  # install cpplint
  - curl https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py > /tmp/cpplint.py
  - sudo mv /tmp/cpplint.py /usr/local/bin/
  - sudo chmod 755 /usr/local/bin/cpplint.py
  # install Google Test
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libgtest* /usr/local/lib/
  # finish before
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir build
  - cd build
  - cmake -D SIO_DIR=$TRAVIS_BUILD_DIR/socket.io-client-cpp/build ..
  - make
  - make doc
  - make cpplint
  - make test
  - ls -l src/core/core
  - src/core/core --help
