language: cpp

env:
  globa:
    - LIBSTDC_VERSION=4.9
    - CLANG_VERSION=3.5

compiler:
  - clang

before_install:
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main" | sudo tee -a /etc/apt/sources.list
  - echo "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:kubuntu-ppa/backports
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -yqq
  - sudo apt-get install -y --allow-unauthenticated pkg-config cmake libgtest-dev doxygen libssl-dev libboost1.55-dev libboost-system1.55-dev libboost-date-time1.55-dev libboost-random1.55-dev automake libtool libncurses5-dev libstdc++-${LIBSTDC_VERSION}-dev clang-${CLANG_VERSION}
  # install socket.io
  - git clone --recurse-submodules https://github.com/socketio/socket.io-client-cpp.git
  - cd socket.io-client-cpp
  - sed -i -e 's/cmake_minimum_required(VERSION 3.1.0/cmake_minimum_required(VERSION 2.8.12/' ./CMakeLists.txt
  - CC=clang-3.5 CXX=clang++-3.5 cmake -D CMAKE_CXX_FLAGS=-std=c++11 .
  - make
  - make install
  - cd $TRAVIS_BUILD_DIR
  # install cpplint
  - curl https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py > /tmp/cpplint.py
  - sudo mv /tmp/cpplint.py /usr/local/bin/
  - sudo chmod 755 /usr/local/bin/cpplint.py
  # install Google Test
  - cd /usr/src/gtest
  - sudo CC=clang-3.5 CXX=clang++-3.5 cmake .
  - sudo make
  - sudo mv libgtest* /usr/local/lib/
  - cd $TRAVIS_BUILD_DIR
  # install libuv
  - curl http://dist.libuv.org/dist/v1.7.5/libuv-v1.7.5.tar.gz > libuv-v1.7.5.tar.gz
  - tar zxf libuv-v1.7.5.tar.gz
  - cd libuv-v1.7.5/
  - sh autogen.sh
  - ./configure
  - make
  - sudo make install
  - cd $TRAVIS_BUILD_DIR
  # patch ubuntu llvm
  - curl https://launchpadlibrarian.net/221945609/fix-llvm-3.5-dev-debian.bash > fix-llvm-3.5-dev-debian.bash
  - sed -i -e 's/llvm-config/llvm-config-3.5/' ./fix-llvm-3.5-dev-debian.bash
  - sh fix-llvm-3.5-dev-debian.bash
  - cd $TRAVIS_BUILD_DIR
  # finish before
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR

script:
  - mkdir build
  - cd build
  - CC=clang-3.5 CXX=clang++-3.5 cmake -D WITH_DOCUMENT=ON -D SIO_DIR=$TRAVIS_BUILD_DIR/socket.io-client-cpp/build ..
  - make
  - make doc
  - make cpplint
  - make test
  - ls -l src/daemon/daemon
  - src/daemon/daemon --help
