language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - clang-3.7
      - cmake

before_install:
  # install cpplint
  - curl https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py > /tmp/cpplint.py
  - sudo mv /tmp/cpplint.py /usr/local/bin/
  - sudo chmod 755 /usr/local/bin/cpplint.py
  # install Google Test
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libgtest* /usr/local/lib/
  - cd $TRAVIS_BUILD_DIR
  # patch ubuntu llvm
  - curl https://launchpadlibrarian.net/221945609/fix-llvm-3.5-dev-debian.bash > fix-llvm-3.5-dev-debian.bash
  - sed -i -e 's/llvm-config/llvm-config-3.5/' ./fix-llvm-3.5-dev-debian.bash
  - sh fix-llvm-3.5-dev-debian.bash
  - cd $TRAVIS_BUILD_DIR
  # finish before
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR

install:
  - sudo script/build.sh
  
script:
  - clang++ --version
  - make cpplint
  - make test
  - ls -l bin
  - bin/processwarp --help
