language: cpp

compiler:
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
      - llvm-toolchain-precise
    packages:
      - clang-3.6

before_install:
  # install cpplint
  - curl https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py > /tmp/cpplint.py
  - sudo mv /tmp/cpplint.py /usr/local/bin/
  - sudo chmod 755 /usr/local/bin/cpplint.py
  # finish before
  - sudo ldconfig
  - cd $TRAVIS_BUILD_DIR
  # update CA
  - wget -q -O $HOME/.cacert.pem http://curl.haxx.se/ca/cacert.pem
  - echo ca-certificate = $HOME/.cacert.pem >> $HOME/.wgetrc

install:
  - sudo script/build.sh
  
script:
  - make cpplint
  - ls -l bin
  - bin/processwarp --help
